# Generated by Django 5.2.1 on 2025-05-27 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destinos',
            fields=[
                ('id_destino', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('localizacao', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'destinos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GuiasLocais',
            fields=[
                ('id_guia', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('especialidade', models.CharField(max_length=100)),
                ('contato', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'guias_locais',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HistoricoViagens',
            fields=[
                ('id_historico', models.AutoField(primary_key=True, serialize=False)),
                ('data_da_viagem', models.DateField()),
                ('avaliacao_da_viagem', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'historico_de_viagens',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ItemRoteiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'item_roteiro',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RoteirosViagens',
            fields=[
                ('id_roteiro', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.DateField()),
                ('descricao', models.TextField()),
            ],
            options={
                'db_table': 'roteiros_de_viagens',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Viajantes',
            fields=[
                ('id_viajante', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('destino_favorito', models.CharField(blank=True, max_length=100, null=True)),
                ('data_de_cadastro', models.DateField()),
            ],
            options={
                'db_table': 'viajantes',
                'managed': False,
            },
        ),
    ]
